spring:
  # redis
  redis:
    host: 118.31.54.149
    port: 8379
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
      shutdown-timeout: 5000
    password: dqhd12138@
  # jdbc 路径
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.31.54.149:3306/suse?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dqhd12138@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#mybatis-plus配置日志
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
  mapper-locations: classpath:/mapper/**.xml
# 日志文件
logging:
  level:
    root: info
    icu.duanqiahang: debug
  file:
    name: newlog/androidService.log
server:
  port: 9001
